# Generated by Django 5.2 on 2025-08-10 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_alter_board_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationUserModel',
        ),
    ]
